mqtt:
  topics:
    brightness_topic: "MQTTAnimator/brightness"
    return_brightness_topic: "MQTTAnimator/rbrightness"
    args_topic: "MQTTAnimator/args"
    animation_topic: "MQTTAnimator/animation"
    return_anim_topic: "MQTTAnimator/ranimation"

gui:
  title: "NeoPixel Animator"
  custom_theming: true
  dark_mode: true
  fullscreen: false
  fixed_size:
    enabled: false
    width: 1024
    height: 600